# Generated by Django 5.0.6 on 2024-06-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploadedfolder_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='UploadedFolder',
        ),
    ]
