# Generated by Django 5.0.6 on 2024-07-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userproject_userid_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='userID',
            new_name='user',
        ),
    ]
