# Generated by Django 5.0.6 on 2024-07-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_userid_userproject_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproject',
            old_name='user',
            new_name='user_id',
        ),
    ]
