# Generated by Django 5.0.6 on 2024-07-24 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_userproject_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, upload_to='savedImages/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userproject')),
            ],
        ),
    ]
