# Generated by Django 5.1 on 2024-08-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_projectimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='YOLOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, upload_to='YOLOV8/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userproject')),
            ],
        ),
    ]
